apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: $DEPLOYMENT_NAME
    spec:
      containers:
        - name: $DEPLOYMENT_NAME
          image: $IMAGE_NAME_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: $DEPLOYMENT_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: $DEPLOYMENT_NAME
  labels:
    app: $DEPLOYMENT_NAME
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: $DEPLOYMENT_NAME

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
  name: $DEPLOYMENT_NAME
spec:
  rules:
    - host: $DEPLOYMENT_NAME.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: $DEPLOYMENT_NAME
                port:
                  number: 5000

