apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DEPLOYMENT_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        app: $DEPLOYMENT_NAME
    spec:
      containers:
        - name: $DEPLOYMENT_NAME
          image: $IMAGE_NAME_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: $DEPLOYMENT_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: $DEPLOYMENT_NAME
  labels:
    app: $DEPLOYMENT_NAME
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 31555
      targetPort: 5000
      name: $DEPLOYMENT_NAME
  selector:
    app: $DEPLOYMENT_NAME
